export const SET_LOGINDETAILS = 'SET_LOGINDETAILS';
export const SET_USERID = 'SET_USERID';
export const SET_ACCEPTEDUSERS = 'SET_ACCEPTEDUSERS';
export const SET_ALLTASKS = 'SET_ALLTASKS';
export const SET_SINGLETASK = 'SET_SINGLETASK';
export const START_SAVE = 'START_SAVE';
